services:
  pdf-converter:
    container_name: pdf-converter
    image: pdf-converter
    build: .
    volumes:
      - ./inputs:/data/inputs
      - ./outputs:/data/outputs
      - ./header.tex:/data/header.tex
      - ./main.py:/data/main.py
      - ./samples:/data/samples
      - ./chars:/data/chars